version: '3.1'

services:

  node:
    build: .
    depends_on:
      - db
    ports:
      - "49160:8080"
    environment:
      DB_HOST: db
  db:
    build: ./database
    container_name: db
    ports: 
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: sample

